### ISSUE TITLE
Color shades are the same for different variants

### ISSUE THREAD

**Issue by travankor** [Eluminae/base16-mako#1]
Gruvbox Dark soft, medium, and hard are exactly the same. Same for Gruvbox Light soft,medium, and hard and Black Metal series.

**Comment by travankor** [comment]
@Eluminae

**Comment by stacyharper** [comment]
This is true with the base16-dunst too. I only chameleoned it :)

**Comment by travankor** [comment]
![2020-03-15-06:54:25AM](https://user-images.githubusercontent.com/38744110/76719847-4f562b00-673b-11ea-981c-c361e37a1966.png)

Any chance you can fix it :) 😼

The theme is inaccurate compared to the rest of sway. 😞

**Comment by stacyharper** [comment]
I do not use base16-mako anymore. Feels free to trick it and I'll forward your fixups here :)

**Comment by travankor** [comment]
>I do not use base16-mako anymore. Feels free to trick it and I'll forward your fixups here :)

What do you use now ?

BTW I sent a PR to fix this.

**Comment by stacyharper** [comment]
I currently am using some very basics colors. I recovered myself from the "I want to customize and unify all my softs" phase :D I am now trying to sticks to defaults the more I can.
Merged!

**Comment by travankor** [comment]
Hmm, I like that idea :)

Except sway and mako have bad defaults :p
